# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 04:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turk', '0003_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='profile',
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
