# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0004_auto_20171124_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.BooleanField(default=False),
        ),
    ]
