# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0006_auto_20171124_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='isClient',
            field=models.BooleanField(default=True),
        ),
    ]
