# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0010_auto_20171124_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
