# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0012_auto_20171124_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='lowest_bid',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='bidders',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.BinaryField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
