# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0013_auto_20171124_2106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bidders',
            new_name='Bidder',
        ),
    ]
