# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0014_auto_20171125_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder',
            name='bidder_name',
        ),
    ]
