# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0016_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='job',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
