# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0017_auto_20171125_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
