# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 04:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turk', '0022_auto_20171126_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormToSuperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing', models.TextField()),
                ('option', models.CharField(choices=[('Not_lowest_bid', 'Not_lowest_bid'), ('Rating_Warning', 'Rating_Warning'), ('Protest_Rating', 'Protest_Rating')], default='Not_lowest_bid', max_length=35)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
