# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0023_formtosuperuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formtosuperuser',
            old_name='option',
            new_name='reason',
        ),
    ]
