# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0027_auto_20171129_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isClient',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
