# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0028_auto_20171130_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
