# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0030_profile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resume',
        ),
    ]
