# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 10:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0038_auto_20171201_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='isHired',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 10, 28, 58, 824946)),
        ),
    ]
