# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 22:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0041_auto_20171203_2145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Developer',
            new_name='DeveloperChosenForJob',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 22, 27, 29, 198812)),
        ),
    ]
