# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 22:54
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0045_auto_20171203_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 22, 54, 35, 639140)),
        ),
    ]
