# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 23:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0046_auto_20171203_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isBlackListed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 23, 53, 33, 131904)),
        ),
    ]
