# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 19:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0047_auto_20171203_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=19)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 19, 39, 14, 921331)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.CharField(choices=[('Being Human', 'Being Human'), ('Software Development', 'Software Development'), ('Video Games', 'Video Games'), ('Social Media', 'Social Media'), ('Food', 'Food'), ('Party', 'Party'), ('Entrepreneurship', 'Entrepreneurship'), ('Money', 'Money')], default='Being Human', max_length=19),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turk.Profile'),
        ),
    ]
