# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 20:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0048_auto_20171205_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 20, 32, 43, 231483)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.TextField(),
        ),
    ]
