# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 21:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0049_auto_20171205_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 21, 0, 10, 807092)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Being Human', 'Being Human'), ('Software Development', 'Software Development'), ('Video Games', 'Video Games'), ('Social Media', 'Social Media'), ('Food', 'Food'), ('Party', 'Party'), ('Entrepreneurship', 'Entrepreneurship'), ('Money', 'Money')], max_length=91),
        ),
    ]
