# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0051_auto_20171206_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterest',
            name='profile',
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 8, 51, 4, 485449)),
        ),
        migrations.DeleteModel(
            name='UserInterest',
        ),
    ]
