# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 09:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0056_auto_20171206_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtosuperuser',
            name='reason',
            field=models.CharField(choices=[('Not_lowest_bid', 'Not_lowest_bid'), ('Rating_Warning', 'Rating_Warning'), ('Protest_Rating', 'Protest_Rating'), ('Protest_Warning', 'Protest_Warning'), ('Quit The System', 'Quit The System')], default='Not_lowest_bid', max_length=35),
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 9, 47, 13, 78278)),
        ),
    ]
