# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 09:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0057_auto_20171206_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtosuperuser',
            name='reason',
            field=models.CharField(choices=[('Not Lowest Bid', 'Not Lowest Bid'), ('Rating Warning', 'Rating Warning'), ('Protest Rating', 'Protest Rating'), ('Protest Warning', 'Protest Warning'), ('Quit The System', 'Quit The System')], default='Not Lowest Bid', max_length=35),
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 9, 48, 4, 316403)),
        ),
    ]
