# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 22:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0058_auto_20171206_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 22, 57, 15, 670281)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5),
        ),
    ]
