# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 02:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0060_auto_20171206_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reason',
            field=models.CharField(choices=[('Warnings', 'Warnings'), ('Jobs', 'Jobs')], default='Temporary', max_length=9),
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 2, 20, 32, 83396)),
        ),
    ]
