# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 05:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turk', '0062_auto_20171207_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsubmission',
            name='user',
        ),
        migrations.AddField(
            model_name='jobsubmission',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 5, 40, 34, 744120)),
        ),
    ]
