# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 05:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0063_auto_20171207_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsubmission',
            old_name='client',
            new_name='developer',
        ),
        migrations.AddField(
            model_name='jobsubmission',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turk.Job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 5, 41, 31, 601988)),
        ),
    ]
