# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0064_auto_20171207_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acc_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 19, 45, 54, 300218)),
        ),
        migrations.AddField(
            model_name='profile',
            name='avg_give_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='honor_Cold_Headed_Tim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='honor_Early_Bird',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='honor_General',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='honor_Hard_Worker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='honor_Job_Supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='honor_Lurker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='honor_MILLIONAIRE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='honor_Normie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='honor_Novice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='honor_Veteran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='honor_toohardman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='money_earned',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_early',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_post',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_post_ex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_give_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='warn_eval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='warn_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='warn_poor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 19, 45, 54, 302638)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
