# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 20:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0065_auto_20171207_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 20, 51, 35, 390678)),
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 20, 51, 35, 390606)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acc_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 20, 51, 35, 387751)),
        ),
    ]
