# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 21:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0066_auto_20171207_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 21, 7, 16, 133187)),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 21, 7, 16, 133219)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acc_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 21, 7, 16, 131618)),
        ),
    ]
