# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0070_auto_20171207_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_rated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 21, 50, 59, 346605)),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 21, 50, 59, 346650)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acc_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 21, 50, 59, 344942)),
        ),
    ]
