# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 22:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0073_auto_20171207_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 22, 19, 21, 607174)),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 22, 19, 21, 607214)),
        ),
        migrations.AlterField(
            model_name='jobsubmission',
            name='submission',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acc_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 22, 19, 21, 605515)),
        ),
    ]
