# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 22:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0074_auto_20171207_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsubmission',
            old_name='submission',
            new_name='file',
        ),
        migrations.AddField(
            model_name='jobsubmission',
            name='note',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 22, 31, 9, 772412)),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 22, 31, 9, 772471)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acc_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 22, 31, 9, 769635)),
        ),
    ]
