# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 22:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0075_auto_20171207_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsubmission',
            old_name='file',
            new_name='submission',
        ),
        migrations.RemoveField(
            model_name='jobsubmission',
            name='note',
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 22, 38, 32, 888846)),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 22, 38, 32, 888910)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acc_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 22, 38, 32, 886167)),
        ),
    ]
