# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 00:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0077_auto_20171207_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerchosenforjob',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobsubmission',
            name='rating',
            field=models.FloatField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
        migrations.AddField(
            model_name='jobsubmission',
            name='reason',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='total_give_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 0, 57, 23, 371255)),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 0, 57, 23, 371292)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acc_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 0, 57, 23, 369420)),
        ),
    ]
