# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 06:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0083_auto_20171208_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 6, 29, 49, 482763)),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 6, 29, 49, 482797)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acc_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 6, 29, 49, 481022)),
        ),
    ]
