# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 00:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0084_auto_20171208_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='warn_money',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 19, 58, 9, 736214)),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 19, 58, 9, 736214)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acc_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 19, 58, 9, 736214)),
        ),
    ]
