# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 01:01
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0085_auto_20171208_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 20, 1, 50, 105120)),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 20, 1, 50, 105120)),
        ),
        migrations.AlterField(
            model_name='job',
            name='lowest_bid',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acc_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 20, 1, 50, 105120)),
        ),
    ]
