# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0087_auto_20171208_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bid_deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 3, 3, 24, 491268)),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 3, 3, 24, 491268)),
        ),
        migrations.AlterField(
            model_name='message',
            name='reason',
            field=models.CharField(choices=[('Poor Performance', 'Poor Performance'), ('Bad Evaluator', 'Bad Evaluator'), ('Not Enough Funds', 'Not Enough Funds'), ('Jobs', 'Jobs')], default='Warnings', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acc_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 3, 3, 24, 489267)),
        ),
    ]
